name: PHP tests
on: [push, pull_request]
jobs:
  # Check there is no syntax errors in the project
  php-linter:
    name: PHP Syntax check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3

      - name: PHP syntax checker 8.1
        uses: prestashop/github-action-php-lint/8.1@master
        with:
          folder-to-exclude: "! -path \"./.github/*\""


  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: xml
      - uses: actions/checkout@v4.1.3
        with:
          fetch-depth: 0

      - run: ./tests/run.sh
